using DomainLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace InfrastructureLayer.Context.Configuratoins
{
    public class NationalityConfiguration : IEntityTypeConfiguration<Nationality>
    {
        public void Configure(EntityTypeBuilder<Nationality> builder)
        {
            builder.HasKey(n => n.Id);


            builder.Property(n => n.Id).ValueGeneratedOnAdd();


            builder.Property(n => n.NationalityName)
                   .HasColumnType("VARCHAR")
                   .HasMaxLength(50)
                   .IsRequired();


            builder.HasData(LoadNationalities());

        }

        private static List<Nationality> LoadNationalities()
        {
            return new List<Nationality>

{
                 new Nationality { Id=1  ,  NationalityName = "Afghanistan"              },
                 new Nationality { Id=2  ,  NationalityName = "Albania"                  },
                 new Nationality { Id=3  ,  NationalityName = "Algeria"                  },
                 new Nationality { Id=4  ,  NationalityName = "Andorra"                  },
                 new Nationality { Id=5  ,  NationalityName = "Angola"                   },
                 new Nationality { Id=6  ,  NationalityName = "Antigua and Barbuda"      },
                 new Nationality { Id=7  ,  NationalityName = "Argentina"                },
                 new Nationality { Id=8  ,  NationalityName = "Armenia"                  },
                 new Nationality { Id=9  ,  NationalityName = "Austria"                  },
                 new Nationality { Id=10 ,  NationalityName = "Azerbaijan"               },
                 new Nationality { Id=11 ,  NationalityName = "Bahrain"                  },
                 new Nationality { Id=12 ,  NationalityName = "Bangladesh"               },
                 new Nationality { Id=13 ,  NationalityName = "Barbados"                 },
                 new Nationality { Id=14 ,  NationalityName = "Belarus"                  },
                 new Nationality { Id=15 ,  NationalityName = "Belgium"                  },
                 new Nationality { Id=16 ,  NationalityName = "Belize"                   },
                 new Nationality { Id=17 ,  NationalityName = "Benin"                    },
                 new Nationality { Id=18 ,  NationalityName = "Bhutan"                   },
                 new Nationality { Id=19 ,  NationalityName = "Bolivia"                  },
                 new Nationality { Id=20 ,  NationalityName = "Bosnia and Herzegovina"   },
                 new Nationality { Id=21 ,  NationalityName = "Botswana"                 },
                 new Nationality { Id=22 ,  NationalityName = "Brazil"                   },
                 new Nationality { Id=23 ,  NationalityName = "Brunei"                   },
                 new Nationality { Id=24 ,  NationalityName = "Bulgaria"                 },
                 new Nationality { Id=25 ,  NationalityName = "Burkina Faso"             },
                 new Nationality { Id=26 ,  NationalityName = "Burundi"                  },
                 new Nationality { Id=27 ,  NationalityName = "Cabo Verde"               },
                 new Nationality { Id=28 ,  NationalityName = "Cambodia"                 },
                 new Nationality { Id=29 ,  NationalityName = "Cameroon"                 },
                 new Nationality { Id=30 ,  NationalityName = "Canada"                   },
                 new Nationality { Id=31 ,  NationalityName = "Central African Republic" },
                 new Nationality { Id=32 ,  NationalityName = "Chad"                     },
                 new Nationality { Id=33 ,  NationalityName = "Channel Islands"          },
                 new Nationality { Id=34 ,  NationalityName = "Chile"                    },
                 new Nationality { Id=35 ,  NationalityName = "China"                    },
                 new Nationality { Id=36 ,  NationalityName = "Colombia"                 },
                 new Nationality { Id=37 ,  NationalityName = "Comoros"                  },
                 new Nationality { Id=38 ,  NationalityName = "Congo"                    },
                 new Nationality { Id=39 ,  NationalityName = "Costa Rica"               },
                 new Nationality { Id=40 ,  NationalityName = "Côte D'Ivoire"            },
                 new Nationality { Id=41 ,  NationalityName = "Croatia"                  },
                 new Nationality { Id=42 ,  NationalityName = "Cuba"                     },
                 new Nationality { Id=43 ,  NationalityName = "Cyprus"                   },
                 new Nationality { Id=44 ,  NationalityName = "Czech Republic"           },
                 new Nationality { Id=45 ,  NationalityName = "Denmark"                  },
                 new Nationality { Id=46 ,  NationalityName = "Djibouti"                 },
                 new Nationality { Id=47 ,  NationalityName = "Dominica"                 },
                 new Nationality { Id=48 ,  NationalityName = "Dominican Republic"       },
                 new Nationality { Id=49 ,  NationalityName = "DR Congo"                 },
                 new Nationality { Id=50 ,  NationalityName = "Ecuador"                  },
                 new Nationality { Id=51 ,  NationalityName = "Egypt"                    },
                 new Nationality { Id=52 ,  NationalityName = "El Salvador"              },
                 new Nationality { Id=53 ,  NationalityName = "Equatorial Guinea"        },
                 new Nationality { Id=54 ,  NationalityName = "Eritrea"                  },
                 new Nationality { Id=55 ,  NationalityName = "Estonia"                  },
                 new Nationality { Id=56 ,  NationalityName = "Eswatini"                 },
                 new Nationality { Id=57 ,  NationalityName = "Ethiopia"                 },
                 new Nationality { Id=58 ,  NationalityName = "Faeroe Islands"           },
                 new Nationality { Id=59 ,  NationalityName = "Finland"                  },
                 new Nationality { Id=60 ,  NationalityName = "France"                   },
                 new Nationality { Id=61 ,  NationalityName = "French Guiana"            },
                 new Nationality { Id=62 ,  NationalityName = "Gabon"                    },
                 new Nationality { Id=63 ,  NationalityName = "Gambia"                   },
                 new Nationality { Id=64 ,  NationalityName = "Georgia"                  },
                 new Nationality { Id=65 ,  NationalityName = "Germany"                  },
                 new Nationality { Id=66 ,  NationalityName = "Ghana"                    },
                 new Nationality { Id=67 ,  NationalityName = "Gibraltar"                },
                 new Nationality { Id=68 ,  NationalityName = "Greece"                   },
                 new Nationality { Id=69 ,  NationalityName = "Grenada"                  },
                 new Nationality { Id=70 ,  NationalityName = "Guatemala"                },
                 new Nationality { Id=71 ,  NationalityName = "Guinea"                   },
                 new Nationality { Id=72 ,  NationalityName = "Guinea Bissau"            },
                 new Nationality { Id=73 ,  NationalityName = "Guyana"                   },
                 new Nationality { Id=74 ,  NationalityName = "Haiti"                    },
                 new Nationality { Id=75 ,  NationalityName = "Holy See"                 },
                 new Nationality { Id=76 ,  NationalityName = "Honduras"                 },
                 new Nationality { Id=77 ,  NationalityName = "Hong Kong"                },
                 new Nationality { Id=78 ,  NationalityName = "Hungary"                  },
                 new Nationality { Id=79 ,  NationalityName = "Iceland"                  },
                 new Nationality { Id=80 ,  NationalityName = "India"                    },
                 new Nationality { Id=81 ,  NationalityName = "Indonesia"                },
                 new Nationality { Id=82 ,  NationalityName = "Iran"                     },
                 new Nationality { Id=83 ,  NationalityName = "Iraq"                     },
                 new Nationality { Id=84 ,  NationalityName = "Ireland"                  },
                 new Nationality { Id=85 ,  NationalityName = "Isle of Man"              },
                 new Nationality { Id=86 ,  NationalityName = "Palestine"                },
                 new Nationality { Id=87 ,  NationalityName = "Italy"                    },
                 new Nationality { Id=88 ,  NationalityName = "Jamaica"                  },
                 new Nationality { Id=89 ,  NationalityName = "Japan"                    },
                 new Nationality { Id=90 ,  NationalityName = "Jordan"                   },
                 new Nationality { Id=91 ,  NationalityName = "Kazakhstan"               },
                 new Nationality { Id=92 ,  NationalityName = "Kenya"                    },
                 new Nationality { Id=93 ,  NationalityName = "Kuwait"                   },
                 new Nationality { Id=94 ,  NationalityName = "Kyrgyzstan"               },
                 new Nationality { Id=95 ,  NationalityName = "Laos"                     },
                 new Nationality { Id=96 ,  NationalityName = "Latvia"                   },
                 new Nationality { Id=97 ,  NationalityName = "Lebanon"                  },
                 new Nationality { Id=98 ,  NationalityName = "Lesotho"                  },
                 new Nationality { Id=99 ,  NationalityName = "Liberia"                  },
                 new Nationality { Id=100,  NationalityName = "Libya"                    },
                 new Nationality { Id=101,  NationalityName = "Liechtenstein"            },
                 new Nationality { Id=102,  NationalityName = "Lithuania"                },
                 new Nationality { Id=103,  NationalityName = "Luxembourg"               },
                 new Nationality { Id=104,  NationalityName = "Macao"                    },
                 new Nationality { Id=105,  NationalityName = "Madagascar"               },
                 new Nationality { Id=106,  NationalityName = "Malawi"                   },
                 new Nationality { Id=107,  NationalityName = "Malaysia"                 },
                 new Nationality { Id=108,  NationalityName = "Maldives"                 },
                 new Nationality { Id=109,  NationalityName = "Mali"                     },
                 new Nationality { Id=110,  NationalityName = "Malta"                    },
                 new Nationality { Id=111,  NationalityName = "Mauritania"               },
                 new Nationality { Id=112,  NationalityName = "Mauritius"                },
                 new Nationality { Id=113,  NationalityName = "Mayotte"                  },
                 new Nationality { Id=114,  NationalityName = "Mexico"                   },
                 new Nationality { Id=115,  NationalityName = "Moldova"                  },
                 new Nationality { Id=116,  NationalityName = "Monaco"                   },
                 new Nationality { Id=117,  NationalityName = "Mongolia"                 },
                 new Nationality { Id=118,  NationalityName = "Montenegro"               },
                 new Nationality { Id=119,  NationalityName = "Morocco"                  },
                 new Nationality { Id=120,  NationalityName = "Mozambique"               },
                 new Nationality { Id=121,  NationalityName = "Myanmar" },
                 new Nationality { Id=122,  NationalityName = "Namibia" },
                 new Nationality { Id=123,  NationalityName = "Nepal" },
                 new Nationality { Id=124,  NationalityName = "Netherlands" },
                 new Nationality { Id=125,  NationalityName = "Nicaragua" },
                 new Nationality { Id=126,  NationalityName = "Niger" },
                 new Nationality { Id=127,  NationalityName = "Nigeria" },
                 new Nationality { Id=128,  NationalityName = "North Korea" },
                 new Nationality { Id=129,  NationalityName = "North Macedonia" },
                 new Nationality { Id=130,  NationalityName = "Norway" },
                 new Nationality { Id=131,  NationalityName = "Oman" },
                 new Nationality { Id=132,  NationalityName = "Pakistan" },
                 new Nationality { Id=133,  NationalityName = "Panama" },
                 new Nationality { Id=134,  NationalityName = "Paraguay" },
                 new Nationality { Id=135,  NationalityName = "Peru" },
                 new Nationality { Id=136,  NationalityName = "Philippines" },
                 new Nationality { Id=137,  NationalityName = "Poland" },
                 new Nationality { Id=138,  NationalityName = "Portugal" },
                 new Nationality { Id=139,  NationalityName = "Qatar" },
                 new Nationality { Id=140,  NationalityName = "Réunion" },
                 new Nationality { Id=141,  NationalityName = "Romania" },
                 new Nationality { Id=142,  NationalityName = "Russia" },
                 new Nationality { Id=143,  NationalityName = "Rwanda" },
                 new Nationality { Id=144,  NationalityName = "Saint Helena" },
                 new Nationality { Id=145,  NationalityName = "Saint Kitts and Nevis" },
                 new Nationality { Id=146,  NationalityName = "Saint Lucia" },
                 new Nationality { Id=147,  NationalityName = "Saint Vincent and the Grenadines" },
                 new Nationality { Id=148,  NationalityName = "San Marino" },
                 new Nationality { Id=149,  NationalityName = "Sao Tome and Principe" },
                 new Nationality { Id=150,  NationalityName = "Saudi Arabia" },
                 new Nationality { Id=151,  NationalityName = "Senegal" },
                 new Nationality { Id=152,  NationalityName = "Serbia" },
                 new Nationality { Id=153,  NationalityName = "Seychelles" },
                 new Nationality { Id=154,  NationalityName = "Sierra Leone" },
                 new Nationality { Id=155,  NationalityName = "Singapore" },
                 new Nationality { Id=156,  NationalityName = "Slovakia" },
                 new Nationality { Id=157,  NationalityName = "Slovenia" },
                 new Nationality { Id=158,  NationalityName = "Somalia" },
                 new Nationality { Id=159,  NationalityName = "South Africa" },
                 new Nationality { Id=160,  NationalityName = "South Korea" },
                 new Nationality { Id=161,  NationalityName = "South Sudan" },
                 new Nationality { Id=162,  NationalityName = "Spain" },
                 new Nationality { Id=163,  NationalityName = "Sri Lanka" },
                 new Nationality { Id=164,  NationalityName = "State of Palestine" },
                 new Nationality { Id=165,  NationalityName = "Sudan" },
                 new Nationality { Id=166,  NationalityName = "Suriname" },
                 new Nationality { Id=167,  NationalityName = "Sweden" },
                 new Nationality { Id=168,  NationalityName = "Switzerland" },
                 new Nationality { Id=169,  NationalityName = "Syria" },
                 new Nationality { Id=170,  NationalityName = "Taiwan" },
                 new Nationality { Id=171,  NationalityName = "Tajikistan" },
                 new Nationality { Id=172,  NationalityName = "Tanzania" },
                 new Nationality { Id=173,  NationalityName = "Thailand" },
                 new Nationality { Id=174,  NationalityName = "The Bahamas" },
                 new Nationality { Id=175,  NationalityName = "Timor-Leste" },
                 new Nationality { Id=176,  NationalityName = "Togo" },
                 new Nationality { Id=177,  NationalityName = "Trinidad and Tobago" },
                 new Nationality { Id=178,  NationalityName = "Tunisia" },
                 new Nationality { Id=179,  NationalityName = "Turkey" },
                 new Nationality { Id=180,  NationalityName = "Turkmenistan" },
                 new Nationality { Id=181,  NationalityName = "Uganda" },
                 new Nationality { Id=182,  NationalityName = "Ukraine" },
                 new Nationality { Id=183,  NationalityName = "United Arab Emirates" },
                 new Nationality { Id=184,  NationalityName = "United Kingdom" },
                 new Nationality { Id=185,  NationalityName = "United States" },
                 new Nationality { Id=186,  NationalityName = "Uruguay" },
                 new Nationality { Id=187,  NationalityName = "Uzbekistan" },
                 new Nationality { Id=188,  NationalityName = "Venezuela" },
                 new Nationality { Id=189,  NationalityName = "Vietnam" },
                 new Nationality { Id=190,  NationalityName = "Western Sahara" },
                 new Nationality { Id=191,  NationalityName = "Yemen" },
                 new Nationality { Id=192,  NationalityName = "Zambia" },
                 new Nationality { Id=193,  NationalityName = "Zimbabwe" }
            };
        }
    }
}
