using DomainLayer.Converters;
using DomainLayer.Entities;
using DomainLayer.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace InfrastructureLayer.Context.Configuratoins
{
    public class StudentCnofiguration : IEntityTypeConfiguration<Student>
    {
        public void Configure(EntityTypeBuilder<Student> builder)
        {
            builder.ToTable("Students");


            builder.ToTable(t => t.HasCheckConstraint("CK_Level_Grade", "([GradeLevel]>=(1) AND [GradeLevel]<=(3))"));


            builder.HasKey(s => s.Id);


            builder.Property(s => s.Id).ValueGeneratedOnAdd();


            builder.Property(s => s.EnrollmentDate).HasColumnType("date").IsRequired();


            builder.Property(s => s.GradeLevel).HasColumnType("tinyint").IsRequired().HasConversion(s => enLevelConverter.Converter(s), s => enLevelConverter.Converter(s));


            builder.HasMany(s => s.MedicalInformationList).WithOne(s => s.Student).HasForeignKey(s => s.StudentID);


            builder.HasOne(s => s.UserInfo).WithOne().HasForeignKey<Student>(s => s.UserID);


            builder.HasData(LoadStudents());

        }
        public static List<Student> LoadStudents()
        {

            return new List<Student>
            {
                new Student { Id = 1   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =1  },
                new Student { Id = 2   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =2  },
                new Student { Id = 3   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =3  },
                new Student { Id = 4   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =4  },
                new Student { Id = 5   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =5  },
                new Student { Id = 6   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =6  },
                new Student { Id = 7   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =7  },
                new Student { Id = 8   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =8  },
                new Student { Id = 9   , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =9  },
                new Student { Id = 10  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =10 },
                new Student { Id = 11  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =11 },
                new Student { Id = 12  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =12 },
                new Student { Id = 13  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =13 },
                new Student { Id = 14  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =14 },
                new Student { Id = 15  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =15 },
                new Student { Id = 16  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =16 },
                new Student { Id = 17  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =17 },
                new Student { Id = 18  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =18 },
                new Student { Id = 19  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =19 },
                new Student { Id = 20  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =20 },
                new Student { Id = 21  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =21 },
                new Student { Id = 22  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =22 },
                new Student { Id = 23  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =23 },
                new Student { Id = 24  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =24 },
                new Student { Id = 25  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =25 },
                new Student { Id = 26  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =26 },
                new Student { Id = 27  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =27 },
                new Student { Id = 28  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =28 },
                new Student { Id = 29  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =29 },
                new Student { Id = 30  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =30 },
                new Student { Id = 31  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =31 },
                new Student { Id = 32  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =32 },
                new Student { Id = 33  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =33 },
                new Student { Id = 34  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =34 },
                new Student { Id = 35  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =35 },
                new Student { Id = 36  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =36 },
                new Student { Id = 37  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =37 },
                new Student { Id = 38  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =38 },
                new Student { Id = 39  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =39 },
                new Student { Id = 40  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =40 },
                new Student { Id = 41  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =41 },
                new Student { Id = 42  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =42 },
                new Student { Id = 43  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =43 },
                new Student { Id = 44  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =44 },
                new Student { Id = 45  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =45 },
                new Student { Id = 46  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =46 },
                new Student { Id = 47  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =47 },
                new Student { Id = 48  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =48 },
                new Student { Id = 49  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =49 },
                new Student { Id = 50  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =50 },
                new Student { Id = 51  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =51 },
                new Student { Id = 52  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =52 },
                new Student { Id = 53  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =53 },
                new Student { Id = 54  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =54 },
                new Student { Id = 55  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =55 },
                new Student { Id = 56  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =56 },
                new Student { Id = 57  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =57 },
                new Student { Id = 58  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =58 },
                new Student { Id = 59  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =59 },
                new Student { Id = 60  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =60 },
                new Student { Id = 61  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =61 },
                new Student { Id = 62  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =62 },
                new Student { Id = 63  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =63 },
                new Student { Id = 64  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =64 },
                new Student { Id = 65  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =65 },
                new Student { Id = 66  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =66 },
                new Student { Id = 67  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =67 },
                new Student { Id = 68  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =68 },
                new Student { Id = 69  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =69 },
                new Student { Id = 70  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =70 },
                new Student { Id = 71  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =71 },
                new Student { Id = 72  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =72 },
                new Student { Id = 73  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =73 },
                new Student { Id = 74  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =74 },
                new Student { Id = 75  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =75 },
                new Student { Id = 76  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =76 },
                new Student { Id = 77  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =77 },
                new Student { Id = 78  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =78 },
                new Student { Id = 79  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =79 },
                new Student { Id = 80  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =80 },
                new Student { Id = 81  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =81 },
                new Student { Id = 82  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =82 },
                new Student { Id = 83  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =83 },
                new Student { Id = 84  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =84 },
                new Student { Id = 85  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =85 },
                new Student { Id = 86  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =86 },
                new Student { Id = 87  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =87 },
                new Student { Id = 88  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =88 },
                new Student { Id = 89  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =89 },
                new Student { Id = 90  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =90 },
                new Student { Id = 91  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =91 },
                new Student { Id = 92  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =92 },
                new Student { Id = 93  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =93 },
                new Student { Id = 94  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =94 },
                new Student { Id = 95  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =95 },
                new Student { Id = 96  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =96 },
                new Student { Id = 97  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =97 },
                new Student { Id = 98  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =98 },
                new Student { Id = 99  , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =99 },
                new Student { Id = 100 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =100},
                new Student { Id = 101 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =101},
                new Student { Id = 102 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =102},
                new Student { Id = 103 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =103},
                new Student { Id = 104 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =104},
                new Student { Id = 105 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =105},
                new Student { Id = 106 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =106},
                new Student { Id = 107 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =107},
                new Student { Id = 108 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =108},
                new Student { Id = 109 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =109},
                new Student { Id = 110 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =110},
                new Student { Id = 111 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =111},
                new Student { Id = 112 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =112},
                new Student { Id = 113 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =113},
                new Student { Id = 114 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =114},
                new Student { Id = 115 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =115},
                new Student { Id = 116 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =116},
                new Student { Id = 117 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =117},
                new Student { Id = 118 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =118},
                new Student { Id = 119 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =119},
                new Student { Id = 120 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =120},
                new Student { Id = 121 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =121},
                new Student { Id = 122 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =122},
                new Student { Id = 123 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =123},
                new Student { Id = 124 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =124},
                new Student { Id = 125 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =125},
                new Student { Id = 126 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =126},
                new Student { Id = 127 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =127},
                new Student { Id = 128 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =128},
                new Student { Id = 129 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =129},
                new Student { Id = 130 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =130},
                new Student { Id = 131 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =131},
                new Student { Id = 132 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =132},
                new Student { Id = 133 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =133},
                new Student { Id = 134 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =134},
                new Student { Id = 135 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =135},
                new Student { Id = 136 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =136},
                new Student { Id = 137 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =137},
                new Student { Id = 138 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =138},
                new Student { Id = 139 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =139},
                new Student { Id = 140 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =140},
                new Student { Id = 141 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =141},
                new Student { Id = 142 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =142},
                new Student { Id = 143 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =143},
                new Student { Id = 144 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =144},
                new Student { Id = 145 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =145},
                new Student { Id = 146 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =146},
                new Student { Id = 147 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =147},
                new Student { Id = 148 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =148},
                new Student { Id = 149 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =149},
                new Student { Id = 150 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =150},
                new Student { Id = 151 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =151},
                new Student { Id = 152 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =152},
                new Student { Id = 153 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =153},
                new Student { Id = 154 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =154},
                new Student { Id = 155 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =155},
                new Student { Id = 156 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =156},
                new Student { Id = 157 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =157},
                new Student { Id = 158 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =158},
                new Student { Id = 159 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =159},
                new Student { Id = 160 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =160},
                new Student { Id = 161 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =161},
                new Student { Id = 162 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =162},
                new Student { Id = 163 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =163},
                new Student { Id = 164 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =164},
                new Student { Id = 165 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =165},
                new Student { Id = 166 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =166},
                new Student { Id = 167 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =167},
                new Student { Id = 168 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =168},
                new Student { Id = 169 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =169},
                new Student { Id = 170 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =170},
                new Student { Id = 171 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =171},
                new Student { Id = 172 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =172},
                new Student { Id = 173 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =173},
                new Student { Id = 174 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =174},
                new Student { Id = 175 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =175},
                new Student { Id = 176 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =176},
                new Student { Id = 177 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =177},
                new Student { Id = 178 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =178},
                new Student { Id = 179 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =179},
                new Student { Id = 180 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =180},
                new Student { Id = 181 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =181},
                new Student { Id = 182 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =182},
                new Student { Id = 183 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =183},
                new Student { Id = 184 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =184},
                new Student { Id = 185 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =185},
                new Student { Id = 186 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =186},
                new Student { Id = 187 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =187},
                new Student { Id = 188 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =188},
                new Student { Id = 189 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =189},
                new Student { Id = 190 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =190},
                new Student { Id = 191 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =191},
                new Student { Id = 192 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =192},
                new Student { Id = 193 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =193},
                new Student { Id = 194 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =194},
                new Student { Id = 195 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =195},
                new Student { Id = 196 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =196},
                new Student { Id = 197 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =197},
                new Student { Id = 198 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =198},
                new Student { Id = 199 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =199},
                new Student { Id = 200 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =200},
                new Student { Id = 201 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =201},
                new Student { Id = 202 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =202},
                new Student { Id = 203 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =203},
                new Student { Id = 204 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =204},
                new Student { Id = 205 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =205},
                new Student { Id = 206 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =206},
                new Student { Id = 207 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =207},
                new Student { Id = 208 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =208},
                new Student { Id = 209 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =209},
                new Student { Id = 210 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =210},
                new Student { Id = 211 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =211},
                new Student { Id = 212 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =212},
                new Student { Id = 213 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =213},
                new Student { Id = 214 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =214},
                new Student { Id = 215 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =215},
                new Student { Id = 216 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =216},
                new Student { Id = 217 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =217},
                new Student { Id = 218 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =218},
                new Student { Id = 219 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =219},
                new Student { Id = 220 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =220},
                new Student { Id = 221 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =221},
                new Student { Id = 222 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =222},
                new Student { Id = 223 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =223},
                new Student { Id = 224 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =224},
                new Student { Id = 225 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =225},
                new Student { Id = 226 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =226},
                new Student { Id = 227 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =227},
                new Student { Id = 228 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =228},
                new Student { Id = 229 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =229},
                new Student { Id = 230 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =230},
                new Student { Id = 231 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =231},
                new Student { Id = 232 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =232},
                new Student { Id = 233 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =233},
                new Student { Id = 234 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =234},
                new Student { Id = 235 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =235},
                new Student { Id = 236 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =236},
                new Student { Id = 237 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =237},
                new Student { Id = 238 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =238},
                new Student { Id = 239 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =239},
                new Student { Id = 240 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =240},
                new Student { Id = 241 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =241},
                new Student { Id = 242 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =242},
                new Student { Id = 243 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =243},
                new Student { Id = 244 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =244},
                new Student { Id = 245 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =245},
                new Student { Id = 246 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =246},
                new Student { Id = 247 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =247},
                new Student { Id = 248 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =248},
                new Student { Id = 249 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =249},
                new Student { Id = 250 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =250},
                new Student { Id = 251 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =251},
                new Student { Id = 252 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =252},
                new Student { Id = 253 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =253},
                new Student { Id = 254 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =254},
                new Student { Id = 255 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =255},
                new Student { Id = 256 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =256},
                new Student { Id = 257 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =257},
                new Student { Id = 258 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =258},
                new Student { Id = 259 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =259},
                new Student { Id = 260 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =260},
                new Student { Id = 261 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =261},
                new Student { Id = 262 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =262},
                new Student { Id = 263 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =263},
                new Student { Id = 264 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =264},
                new Student { Id = 265 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =265},
                new Student { Id = 266 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =266},
                new Student { Id = 267 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =267},
                new Student { Id = 268 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =268},
                new Student { Id = 269 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =269},
                new Student { Id = 270 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =270},
                new Student { Id = 271 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =271},
                new Student { Id = 272 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =272},
                new Student { Id = 273 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =273},
                new Student { Id = 274 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =274},
                new Student { Id = 275 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =275},
                new Student { Id = 276 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =276},
                new Student { Id = 277 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =277},
                new Student { Id = 278 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =278},
                new Student { Id = 279 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =279},
                new Student { Id = 280 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =280},
                new Student { Id = 281 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =281},
                new Student { Id = 282 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =282},
                new Student { Id = 283 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =283},
                new Student { Id = 284 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =284},
                new Student { Id = 285 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =285},
                new Student { Id = 286 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =286},
                new Student { Id = 287 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =287},
                new Student { Id = 288 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =288},
                new Student { Id = 289 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =289},
                new Student { Id = 290 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =290},
                new Student { Id = 291 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =291},
                new Student { Id = 292 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =292},
                new Student { Id = 293 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =293},
                new Student { Id = 294 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =294},
                new Student { Id = 295 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =295},
                new Student { Id = 296 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =296},
                new Student { Id = 297 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =297},
                new Student { Id = 298 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =298},
                new Student { Id = 299 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)1, UserID =299},
                new Student { Id = 300 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)2, UserID =300},
                new Student { Id = 301 , EnrollmentDate = DateTime.Now, GradeLevel =(enLevel)3, UserID =301}


            };
        }
    }



}
